- src/parser/constructs.rs
> function_call: Allow calls with no arguments but spaces

- src/parser/box_construct.rs
- src/parser/constructs.rs
> Add parsing logic for field access

- Cargo.lock
- Cargo.toml
- src/indent.rs
- src/instance/mod.rs
- src/instruction/field_access.rs
- src/instruction/type_instantiation.rs
- src/instruction/var.rs
- src/main.rs
- src/repl.rs
This PR adds more typing to instances. Instead of simply keeping track of the offset and size of the data and fields, we can also keep track of the instance in itself. This is slower but helps keep more information that we might need (such as the type of said instance)
> Typed instances

- SYNTAX.md
The for-loop example was treating ranges as if they included their upper bound.
> Fix semi-open range

- src/value/jk_constant.rs
- typechecker: Add base trait for TypeChecking
- typechecker: Add type_cache macro
- typechecker: Add default() for CheckedType
- typechecker: Add documentation
- typechecker: Fix formatting
- repl: Do not execute if a type error was found
- repl: Emit errors in interactive mode
- typechecker: Remove trait bound on TC for Instructions
- cargo: Update jinko version
- repl: Remove usage of typechecking for now
- binary_op: Remove warnings
- jk_inst: Remove warnings
- typechecker: Remove Typechecker uses for now
- jk_constant: Implement typechecking
> Typecheck constants

- src/instruction/jk_inst.rs
- src/instruction/var_assignment.rs
- src/parser/box_construct.rs
- src/parser/constructs.rs
- src/parser/ebnf_grammar
- src/parser/shunting_yard.rs
- src/parser/tokens.rs
Current parser backtraces causing evaluation to run in polynomial time, maybe even exponential time in some cases.
We can rework the grammar to run in linear time, thus drastically increasing performance.
> Rework parser

- src/args.rs
- src/context.rs
- src/main.rs
- src/parser/mod.rs
- src/utils.rs
- tests/ft/stdlib/stdlib.yml
Closes #234.
This adds the `-no-std` flag to jinko. In order to do this, the context creation had to be moved out of the parsing function.
> Add `--no-std` option

- src/parser/constructs.rs
- src/parser/tokens.rs
Fixes #340.
Only accept tokens that match and don't have an alphanumeric or `_` character after.
> Only fail token parsing if alphanum_ is next

- stdlib/lib.jk
- tests/ft/regression/187_fn.jk
- tests/ft/stdlib/maybe.jk
- tests/ft/type_checking/valid/field_access.jk
- tests/ft/type_checking/valid/function_complex_type.jk
- tests/ft/type_checking/valid/function_type_mapping.jk
- tests/ft/type_checking/valid/return_in_if_else.jk
- stdlib: Remove extraneous @dump() instruction
- 187_fn: Fix block syntax for inner function declaration
- maybe: Adapt code to new type instantiation syntax
- field_access: Use new type instantiation syntax
- cinop: Use new type instantiation syntax
- type_mapping: New block syntax returns value despite semicolon, adapt test
- if_else: Fix syntax in if_else return test
> Fix functional tests in new parser

- Dockerfile
This is just a simple Dockerfile to run the jinko interpreter directly.
I tried splitting it in two (one layer for build, and one for run) but without any success, I guess the binary cannot be run without rust libraries.
Tell me what you think and I shall adjust my pull request to please your needs.
> docker: add basic Dockerfile to run jinko interpreter

- .github/workflows/build_test_fmt.yml
- .github/workflows/clippy.yml
- src/instruction/mod.rs
- src/instruction/var_or_empty_type.rs
- src/parser/constructs.rs
- stdlib/maybe.jk
- stdlib/pair.jk
- tests/ft/type_checking/invalid/empty_types.jk
- tests/ft/type_checking/typecheck.yml
- tests/ft/type_checking/valid/empty_types.jk
The issue we are facing right now is differentiating between variables
and empty types instantiation. For example, `a = Type;` is no different,
parser wise, from `a = b;`. We can differentiate this later on during
typechecking or find another solution here
> Parse and instantiate empty types

- src/instruction/function_call.rs
- src/instruction/method_call.rs
- parser: WIP: Parse empty types -> Read message
- empty_types: Add empty type parsing and instantiation
- empty_types: Instantiate empty types on the fly
- functions: Allow as_bool() on function calls and method calls
> Allow function calls as booleans

- src/builtins.rs
- stdlib/args.jk
- tests/ft/stdlib/args.jk
- parser: WIP: Parse empty types -> Read message
- empty_types: Add empty type parsing and instantiation
- empty_types: Instantiate empty types on the fly
- stdlib: Add Args.count() function
- stdlib: Make Args type an empty type
> Add Args.count()

- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/function_call.rs
- src/instruction/if_else.rs
- src/instruction/loop_block.rs
- src/instruction/method_call.rs
- src/instruction/mod.rs
- src/instruction/var.rs
- src/instruction/var_or_empty_type.rs
- src/value/jk_constant.rs
> Remove as_bool in Instruction trait

- Cargo.lock
- Cargo.toml
- interpreter/jinko.rs
- interpreter/repl.rs
- src/context.rs
- src/ffi.rs
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/extra_content.rs
- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/incl.rs
- src/instruction/jk_inst.rs
- src/instruction/loop_block.rs
- src/instruction/method_call.rs
- src/instruction/type_declaration.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/lib.rs
- src/log.rs
- src/parser/mod.rs
- src/value/jk_constant.rs
- log: Add basic logging macro
- ctx: Remove set_debug() function
- log: Replace ctx.debugs() with simple logging
Closes #64 
This enables various passes to not rely on the context for logging anymore. It's currently very simple, but we could think about improving it later on
> Add simple logging system

- src/parser/constant_construct.rs
- src/parser/constructs.rs
- src/parser/grammar
This PR formats string at parse time instead of eval time,
here's an example change in behavior caused by this PR:
before:
```
my_str = "{wont_fail}"
wont_fail = 10
println(my_str)
```
after:
```
my_str = "{will_fail}"
will_fail = 10
println(my_str)
```
The big difference it this string is now formatted in the context where it is ***built*** instead on where it is ***called***.
I'm not sure if/what could I should remove to disable de eval time formatting though.
> Format string on parsing

- Cargo.lock
- Cargo.toml
- interpreter/jinko.rs
- src/builtins.rs
- src/context.rs
- src/error/mod.rs
- src/instruction/function_call.rs
- src/lib.rs
To test this, compile with:
``cargo build --no-default-features``
> Add ffi and repl features

- Cargo.lock
- interpreter/repl.rs
- src/builtins.rs
- src/context.rs
- src/error/mod.rs
- src/instruction/block.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/incl.rs
- src/typechecker.rs
- src/value/jk_constant.rs
The only issue remaining with this change is figuring out how to include code properly. I think this shows that loading the code at each path from a different file is faaaar from optimal, and that maybe we should run an "inclusion pass" akin to the C preprocessor before the typechecking and execution passes. This pass would simply do nothing but append nodes to a mutable vector or to the context's entry point
> typechecker: WIP Move TypeCtx inside Context structure

- Cargo.lock
- examples/simple-repl.rs
- src/context.rs
In order to make repl.jinko.ml to work correctly, we need to have an `eval` function. 
For now I think that `Context` is a good home. But I will let this in draft until the code architecture refactor is done.
We also need to figure out how we want to be able to log error and ouptut somewhere else than `stdout` and `stderr`
> Add eval funtion

- interpreter/repl.rs
- src/context.rs
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/extra_content.rs
- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/incl.rs
- src/instruction/jk_inst.rs
- src/instruction/jk_return.rs
- src/instruction/loop_block.rs
- src/instruction/method_call.rs
- src/instruction/type_declaration.rs
- src/instruction/type_id.rs
- src/instruction/type_instantiation.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/instruction/var_or_empty_type.rs
- src/typechecker.rs
- src/value/jk_constant.rs
To allow later passes to access the type of an instruction without needing to perform the typechecking again, cache the type of each instruction *in* the instruction. This PR adds *a lot* of mutability which I am not happy with, but makes genericity possible. I have no idea how to do this without mutability or the repetition of a typechecking pass during the generic pass
> Keep type in instruction

- interpreter/jinko.rs
- src/instance/mod.rs
- src/instruction/binary_op.rs
- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/incl.rs
- src/instruction/type_instantiation.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/instruction/var_or_empty_type.rs
- src/typechecker.rs
This PR adds a new variant to the `CheckedType` enum. Its usage is described in the documentation of the `resolve_type()` trait function
> Add `CheckedType::Later`

- src/instruction/function_call.rs
- tests/ft/generics/generics.yml
- tests/ft/generics/valid_call_generic_twice.jk
- generics: WIP allow calling and declaring generic functions
- generics: Remove `generate_new()` trait function
- generics: Add functional test directory
- generics: Return CheckedType::Later in generic funcdec
- generics: Add test for calling the same generic twice
- function_call: Do not recreate generic if it is already present
> Do not declare generic functions twice

- interpreter/jinko.rs
- src/context.rs
- src/generics.rs
- src/instruction/block.rs
- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/method_call.rs
- src/instruction/mod.rs
- src/instruction/var_assignment.rs
- src/instruction/var_or_empty_type.rs
- src/typechecker.rs
- tests/ft/generics/valid_multiple_ducktyping.jk
- tests/func_tests.sh
This PR cleans up the generic implementation to add new nodes to the outermost scope, in order to make them available even after type checking
> Cleanup generic implementation

- src/ffi.rs
> Comment `link_with("libc.so.6")` in ffi testsuite

- src/error/mod.rs
- src/generics.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/jk_inst.rs
- src/instruction/operator.rs
- src/instruction/type_declaration.rs
- src/typechecker.rs
- src/utils.rs
- src/value/jk_constant.rs
- stdlib/lib.jk
As mentioned in https://github.com/jinko-core/jinko/issues/568, including the vec implementation forces a link with the `libc.so.6`, this breaks a lot of stuff, including the docker image and the usage of Jinko on machines not having the given lib.
> Disable vec include in stdlib

- .github/workflows/release.yml
Imho, we should not trust the action used to publish the crate, it is very easy for the creator to start doing some shady stuff and override the given tag so our call to his action does the shady stuff.
Also, it is even easier and shorter to publish the crate ourselves with the usual `cargo publish` command.
Do not worry about the secret, I have set it up before creating the PR. 
Also, the job was failing before the `CARGO_REGISTRY_TOKEN` was not registered in the repository secrets.
Fyi, this should fix https://github.com/jinko-core/jinko/runs/8036624585?check_suite_focus=true
> ci: release on crates.io manually instead of using untrusted action

- src/builtins.rs
- src/context.rs
- src/instruction.rs
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/dec_arg.rs
- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/incl.rs
- src/instruction/jk_inst.rs
- src/instruction/jk_return.rs
- src/instruction/loop_block.rs
- src/instruction/method_call.rs
- src/instruction/type_declaration.rs
- src/instruction/type_instantiation.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/instruction/var_or_empty_type.rs
- src/lib.rs
- src/typechecker.rs
- src/typechecker/type_id.rs
- src/value/jk_constant.rs
- tests/ft/generics/generics.yml
- tests/ft/regression/regression.yml
In accordance with this writeup https://docs.jinko.ml/writeups/4-error-handling-inside-the-interpreter/
This now also removes generics as they are a pain in the ass and are implemented incorrectly.
Fixes #587
> Do proper aggregation sites and emission sites when emitting errors

- ast-sanitizer/src/lib.rs
- error/src/lib.rs
- fir/src/iter/mapper.rs
- fir/src/lib.rs
- flatten/src/lib.rs
- include_code/src/lib.rs
- interpreter/jinko.rs
- name_resolve/src/declarator.rs
- name_resolve/src/lib.rs
- name_resolve/src/resolver.rs
- recursive_typecheck/src/lib.rs
- typecheck/src/actual.rs
- typecheck/src/checker.rs
- typecheck/src/lib.rs
- typecheck/src/typer.rs
- xparser/src/lib.rs
The `Fir` will now be able to access AST nodes even deep in the pipeline, and to do so cheaply by just accessing a reference.
In the immediate future, this is useful for typechecking constants and accessing builtin types.
- fir: Remove Default bounds where possible
- flatten: Keep AST information in FlattenData
- flatten: Add new AstInfo enum
- ast-sanitizer: Use new Flatten API
- include_code: Use new Flatten API
- interpreter: Use new Flatten API
- error: Add new with_opt_loc function, depreciate it
- flatten: Add note about symbols from Constants
- name_resolve: Use new Flatten API
- typecheck: Use new Flatten API
- xparser: Add new ast!() macro
- name_resolve: Use xparser::ast! macro
- flatten: Fix AstInfo::symbol in some cases
- rec_typecheck: Use new Flatten API
> Flatten: keep references to the AST throughout

- Cargo.lock
- fir/src/checks.rs
- flatten/src/lib.rs
- typecheck/Cargo.toml
- typecheck/src/lib.rs
- typecheck/src/primitives.rs
- typecheck/src/typer.rs
This now allows the typechecker to recognize our primtive types and resolve the type of constants/literals.
> typecheck: Allow proper typechecking of primitive types

- fir/src/lib.rs
- flatten/src/lib.rs
- name_resolve/src/declarator.rs
- name_resolve/src/lib.rs
- name_resolve/src/resolver.rs
- name_resolve/src/scoper.rs
- typecheck/src/actual.rs
- typecheck/src/checker.rs
- typecheck/src/primitives.rs
- name-resolve: Add `Scoper` pass
- fir: Allowing index through Fir with RefIdx
- fir: Allow indexing with RefIdx, rename `RefIdx::unwrap`
- [f] name_resolve: Add base for new scope maps and algorithms
> Fix function binding name resolution

- Cargo.lock
- Cargo.toml
- fir/src/checks.rs
- fire/Cargo.toml
- fire/src/instance.rs
- fire/src/lib.rs
- interpreter/jinko.rs
- name_resolve/src/lib.rs
- typecheck/src/actual.rs
- typecheck/src/checker.rs
- typecheck/src/lib.rs
- typecheck/src/typer.rs
- xparser/src/lib.rs
- fire: Add extremely basic interpretation engine
- fire: Start performing calls to builtin functions
- fire: Add proper tree-like interpretation
- fire: wip: Add more comments regarding execution
Fixes #615
Fixes #618
> Add simple Fir executor

- fire/src/instance.rs
- fire/src/lib.rs
- name_resolve/src/scoper.rs
This PR allows early returns from functions, as well as adds machinery for doing the same with break and continue expressions
> fire: Add early returns

- ast/src/lib.rs
- builtins/src/builder.rs
- fire/src/lib.rs
- flatten/src/lib.rs
- name_resolve/src/lib.rs
- name_resolve/src/resolver.rs
- xparser/src/constructs.rs
- xparser: Parse multi types properly
- ast: Add note about renaming TypeArgument
- flatten: Add handling for AST types
- [wip]: from this point on in the log I'm buzzed
- flatten: [wip] Start handling TypeFields properly
- xparser: Generate proper TypeField
- fir: Rename Kind::Type to Kind::RecordType
- fir: Add Kind::UnionType
- fir: [wip] Fix checks for union types
- flatten: Handle multi-types properly
- name_resolve: [wip]: add tests
> Name resolve multi types

- Cargo.lock
- ast/src/lib.rs
- fir/src/checks.rs
- fir/src/lib.rs
- fire/src/lib.rs
- flatten/src/lib.rs
- name_resolve/Cargo.toml
- name_resolve/src/declarator.rs
- name_resolve/src/lib.rs
- name_resolve/src/resolver.rs
- typecheck/src/actual.rs
- typecheck/src/checker.rs
- typecheck/src/lib.rs
- typecheck/src/primitives.rs
- typecheck/src/typemap.rs
- typecheck/src/typer.rs
- [wip]: Start working on type var interpreter. Bring over UnionType from FIR
- [wip]: Go further with the typelevel interpreter
- [wip] it compiles
- [wip]: Improve errors and API
- wip: Add proper handling of Kind::UnionType
- [wip] almost there
- [wip] it fucken works ~ ! ! ~
- typecheck: Start adding TypeMap data structure
- typecheck: Start making TypeCtx generic
> Implement base type-level interpreter and subtyping

- debug-fir/src/lib.rs
- fir/src/checks.rs
- fir/src/iter/mapper.rs
- fir/src/iter/multi_mapper.rs
- fir/src/iter/traverse.rs
- fir/src/lib.rs
- fire/src/lib.rs
- flatten/src/lib.rs
- interpreter/jinko.rs
- name_resolve/src/declarator.rs
- name_resolve/src/lib.rs
- name_resolve/src/resolver.rs
- name_resolve/src/scoper.rs
- recursive_typecheck/src/lib.rs
- typecheck/src/typer.rs
Fixes #661 
Can we actually remove `ValueRef`/`TypedValue`? I don't think we need it, since we should just be able to keep a `RefIdx` of a binding.
> Fix relationship between `Kind::Binding` and `Kind::TypedValue`
