jinko-core/jinko

- src/parser/constructs.rs
> parser: Fix function calls with only one arg

- src/parser/constructs.rs
> constructs: Add test for mut <\n> var

- src/instruction/binary_op.rs
- src/instruction/function_call.rs
- src/instruction/var_assignment.rs
- src/parser/constructs.rs
> tests: De-ignore all tests except unimplemented ones

- README.md
Hey, I am pretty new to contribution so any tip will be appreciated!
> resized logo in readme

- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/parser/box_construct.rs
- src/parser/constructs.rs
> Map function arguments to block

- src/instance/mod.rs
- src/instruction/audit.rs
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/loop_block.rs
- src/instruction/mod.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/main.rs
- src/parser/jinko_insts.rs
- src/repl/mod.rs
- src/value/jink_bool.rs
- src/value/jink_char.rs
- src/value/jink_float.rs
- src/value/jink_int.rs
- src/value/jink_string.rs
> Make Instruction::execute() return an Instance

- src/instruction/function_call.rs
- src/instruction/var_assignment.rs
- src/main.rs
- src/value/jink_float.rs
- src/value/jink_int.rs
> Allow compilation with stable Rust release

- src/instance/mod.rs
- src/instruction/block.rs
- src/instruction/mod.rs
- src/parser/constructs.rs
> Execution v0.1.0 use block last exp as return

- src/instance/mod.rs
- src/instruction/block.rs
- src/instruction/var.rs
- src/main.rs
> execution v0.1.0 represent vars correctly

- src/instruction/block.rs
- src/instruction/function_call.rs
- src/instruction/mod.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/interpreter/mod.rs
- src/interpreter/scope_map.rs
- src/parser/constructs.rs
- src/parser/shunting_yard.rs
> execution v0.1.0 assign vars

- src/instruction/binary_op.rs
- src/parser/shunting_yard.rs
- src/utils/queue.rs
> fix shunting yard

- LICENSE
> license: Add GPLV2.0 license

- src/instruction/loop_block.rs
> Mark for loop as unavailable

- .github/workflows/release.yml
- DESIGN.md
- src/args.rs
- src/error/mod.rs
- src/instance/mod.rs
- src/instruction/audit.rs
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/jk_inst.rs
- src/instruction/loop_block.rs
- src/instruction/mod.rs
- src/instruction/operator.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/interpreter/mod.rs
- src/interpreter/scope_map.rs
- src/main.rs
- src/parser/box_construct.rs
- src/parser/constant_construct.rs
- src/parser/constructs.rs
- src/parser/jinko_insts.rs
- src/parser/mod.rs
- src/parser/shunting_yard.rs
- src/repl/mod.rs
- src/value/jink_constant.rs
- src/value/jk_constant.rs
- src/value/mod.rs
Closes #68 
Closes #121
Closes #95
> Import export cleanup

- src/parser/constructs.rs
- src/parser/shunting_yard.rs
> Fix shunting yard eager consumption

- ARCHITECTURE.md
- CONTRIBUTING.md
- README.md
> Add better support for new contributors

- src/repl/mod.rs
> Fix old documentation in REPL

- src/instruction/block.rs
> Fix block documentation

- src/instruction/field_access.rs
- src/parser/constructs.rs
> field_access: Allow field accesses on type instantiations

- src/args.rs
- src/context.rs
- src/context/scope_map.rs
- src/error/mod.rs
- src/instance/mod.rs
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/extra_content.rs
- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/incl.rs
- src/instruction/jk_inst.rs
- src/instruction/loop_block.rs
- src/instruction/method_call.rs
- src/instruction/mod.rs
- src/instruction/type_declaration.rs
- src/instruction/type_instantiation.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/main.rs
- src/parser/constructs.rs
- src/parser/mod.rs
- src/parser/shunting_yard.rs
- src/repl/mod.rs
- src/repl/prompt.rs
- src/value/jk_constant.rs
- src/value/mod.rs
- context: Rename interpreter -> context, fix documentation
- context: Rename usages of i|interpreter to ctx
- context: Remove in_audit field
> Improve Context usage

- Cargo.lock
- Cargo.toml
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/dec_arg.rs
- src/instruction/extra_content.rs
- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/instruction/if_else.rs
- src/instruction/incl.rs
- src/instruction/jk_inst.rs
- src/instruction/loop_block.rs
- src/instruction/method_call.rs
- src/instruction/mod.rs
- src/instruction/rename.rs
- src/instruction/type_declaration.rs
- src/instruction/type_id.rs
- src/instruction/type_instantiation.rs
- src/instruction/var.rs
- src/instruction/var_assignment.rs
- src/main.rs
- src/value/jk_constant.rs
- tests/ft/incl/incl_dir_includer.jk
- tests/ft/incl/incl_dir_subfile_includer.jk
- tests/ft/incl/incl_simple_includer.jk
- tests/ft/namespaces/lib/lib.jk
- tests/ft/namespaces/nspace_alias_includer.jk
- tests/ft/namespaces/nspace_method_call.jk
- tests/ft/namespaces/nspace_no_alias_includer.jk
- jinko: WIP: Remove name prefixing
- cargo: Bump to 0.2.2
> Remove name prefixing

- src/instruction/field_access.rs
- src/instruction/jk_return.rs
- src/parser/mod.rs
> Add jinko! test macro

- src/context.rs
- src/context/scope_map.rs
The type context will also need a scope map, using different types than `Vars`, `TypeDecs` and `FunctionDecs`
> Improve scope map for future `TypeCtx`

- src/context.rs
- src/context/scope_map.rs
- src/instruction/binary_op.rs
- src/instruction/block.rs
- src/instruction/if_else.rs
- src/instruction/loop_block.rs
- src/main.rs
- src/typechecker.rs
- src/value/jk_constant.rs
- typechecker: Add basic TypeCtx type
- instructions: Use TypeCtx instead of Context
> Add Type Context

- src/instruction/type_declaration.rs
- src/instruction/type_id.rs
- src/instruction/type_instantiation.rs
- type_id: Add conversion from TypeDec to TypeId
- type_declaration: Implement typechecking
- type_instantiation: Implement typechecking
- type_instantiation: Typecheck field values
> TypeInstantiation: Implement typechecking

- src/instruction/jk_return.rs
> return: Implement typechecking

- src/instruction/method_call.rs
> method_call: Implement typechecking

- src/instruction/incl.rs
> incl: Implement typechecking

- src/context.rs
- src/instruction/block.rs
- src/instruction/if_else.rs
- src/instruction/loop_block.rs
- src/instruction/var_assignment.rs
- src/parser/constructs.rs
- src/parser/grammar
> Support block statements

- src/parser/constructs.rs
- src/parser/grammar
> Refactor spaced identifiers into own function

- DESIGN.md
- SYNTAX.md
> generics: Update DESIGN and SYNTAX

- Dockerfile
Let's be stable for a second...
> docker: fix deployed image

- Cargo.lock
- Cargo.toml
Added new improved parser from @SanderJSA
> Release v0.3.0-jinx1

- Cargo.toml
> Switch to Rust edition 2021

- src/instruction/mod.rs
- src/instruction/var_or_empty_type.rs
- src/parser/constructs.rs
- stdlib/lib.jk
- stdlib/maybe.jk
- stdlib/pair.jk
- tests/ft/type_checking/invalid/empty_types.jk
- tests/ft/type_checking/typecheck.yml
- tests/ft/type_checking/valid/empty_types.jk
- parser: WIP: Parse empty types -> Read message
- empty_types: Add empty type parsing and instantiation
- empty_types: Instantiate empty types on the fly
- stdlib: Add NoReturn type
> Add `NoReturn` type

- src/instruction/loop_block.rs
- tests/ft/regression/276.jk
- tests/ft/regression/284.jk
- tests/ft/regression/306.jk
- tests/ft/regression/320.jk
- tests/ft/regression/regression.yml
Closes #338
Closes #320
Closes #276
Closes #306
Closes #284
> Resolve fixed parser issues

- interpreter/args.rs
- interpreter/jinko.rs
- src/context.rs
- src/lib.rs
- tests/ft/unit_testing/unit_testing.yml
- tests/ft/unit_testing/valid/multi_tests.jk
- tests/ft/unit_testing/valid/one_test.jk
- jinko: Expose more modules in the crate
- interpreter: Run tests on --test flag
- tests: Unit test tests
> Add --test flag to the interpreter

- src/builtins.rs
- tests/ft/stdlib/args.jk
- tests/ft/stdlib/stdlib.yml
> Fix arg_get builtin

- src/parser/tokens.rs
> Fix empty string parsing

- .github/workflows/docker.yml
> Publish docker images for latest and bleeding

- src/parser/constant_construct.rs
- src/parser/tokens.rs
> Support character escaping in strings

- interpreter/repl.rs
- src/context.rs
> repl: Include stdlib and typecheck properly

- src/instruction/field_access.rs
- src/instruction/function_call.rs
- src/instruction/if_else.rs
- src/instruction/method_call.rs
- tests/ft/generics/generics.yml
- tests/ft/generics/valid_field_access.jk
- tests/ft/generics/valid_if_else.jk
- tests/ft/generics/valid_method_call.jk
> Expand generics in more instructions

- src/instruction/function_call.rs
> Fix overzealous generic mapping

- src/instruction/incl.rs
> incl: Fix code inclusion

- src/instruction/function_declaration.rs
- tests/ft/regression/468.jk
- tests/ft/regression/regression.yml
- tests/ft/type_checking/invalid/test_f.jk
- tests/ft/type_checking/typecheck.yml
> Do not declare test functions in type context

- src/instruction/function_call.rs
- tests/ft/regression/462.jk
- tests/ft/regression/regression.yml
> Forbid generic calls on non generic decls

- src/instruction/block.rs
- src/instruction/function_call.rs
- src/instruction/function_declaration.rs
- src/typechecker.rs
- tests/ft/generics/generics.yml
- tests/ft/generics/invalid_typechecking.jk
- tests/ft/generics/valid_multiple_ducktyping.jk
> Typecheck generic functions properly

- interpreter/args.rs
- interpreter/jinko.rs
- src/context.rs
- tests/ft/options/display_str.jk
- tests/ft/options/options.yml
- tests/ft/options/return_2.jk
- tests/ft/stdlib/stdlib.yml
> Add --check

- Dockerfile
> docker: enable repl feature

- src/error/mod.rs
> hints: Add source file to error message

- ARCHITECTURE.md
> Architecture fix

- src/typechecker/type_id.rs
> type_id: Refactor implementation

- src/instruction/var_assignment.rs
- src/parser/constructs.rs
Fixes #522 
Co-authored-by: CohenArthur <arthur.cohen@embecosm.com>
> typechecker: Fix statement assignment to variables

- src/error/mod.rs
- src/instruction/type_instantiation.rs
- src/instruction/var_assignment.rs
- src/parser/constructs.rs
- src/typechecker.rs
- tests/ft/errors/errors.yml
- tests/ft/errors/stress.jk
This removes some highlighting and lines of dashes to make the output simpler and cleaner
> Improve error format when emitting

- Cargo.lock
- Cargo.toml
> Release v0.3.0-jinx5

- Cargo.lock
- Cargo.toml
Should fix the release workflow
> Release v0.3.0-jinx6

- Cargo.lock
- Cargo.toml
Fixes the crate publishing workflow
> Prepare release v0.3.0-jinx7

- src/value/jk_constant.rs
Needs #550 
Only review the last commit
> Cleanup jk constant

- ast/src/lib.rs
- fir/src/checks.rs
- fir/src/lib.rs
- flatten/src/lib.rs
- xparser/src/tokens.rs
Cherry-picked directly from #591
> Implement flatten properly

- Cargo.lock
- ast/src/lib.rs
- fir/src/checks.rs
- fir/src/lib.rs
- flatten/Cargo.toml
- flatten/src/lib.rs
- loop_desugar/src/lib.rs
- xparser/src/constructs.rs
- xparser/src/tokens.rs
> Add starting point for `where` declarations

- Cargo.lock
- Cargo.toml
- ast/src/lib.rs
- debug-fir/Cargo.toml
- debug-fir/src/lib.rs
- error/src/lib.rs
- fir/src/checks.rs
- fir/src/iter.rs
- fir/src/iter/mapper.rs
- fir/src/iter/multi_mapper.rs
- fir/src/iter/traverse.rs
- fir/src/iter/visitor.rs
- fir/src/lib.rs
- flatten/src/lib.rs
- interpreter/jinko.rs
- location/src/lib.rs
- name_resolve/Cargo.toml
- name_resolve/src/declarator.rs
- name_resolve/src/lib.rs
- name_resolve/src/resolver.rs
- symbol/src/lib.rs
- xparser/src/constructs.rs
- xparser/src/tokens.rs
> Fir: Add mapping functions and name-resolving

- debug-fir/src/lib.rs
- fir/src/checks.rs
- fir/src/iter/mapper.rs
- fir/src/iter/multi_mapper.rs
- fir/src/iter/traverse.rs
- fir/src/lib.rs
- fire/src/lib.rs
- flatten/src/lib.rs
- name_resolve/src/declarator.rs
- name_resolve/src/lib.rs
- name_resolve/src/scoper.rs
- recursive_typecheck/src/lib.rs
- typecheck/src/actual.rs
- typecheck/src/lib.rs
- typecheck/src/primitives.rs
- typecheck/src/typer.rs
This adds a new type of node to the FIR specifically aimed at sum types/union types/multi types
> Add `fir::Kind::UnionType`

- Cargo.lock
- ast/src/lib.rs
- fir/src/checks.rs
- flatten/src/lib.rs
- name_resolve/Cargo.toml
- name_resolve/src/declarator.rs
- name_resolve/src/lib.rs
- xparser/src/constructs.rs
> Handle type literals in name resolution
